version: '3.9'

services:
  postgres:
    container_name: ecommerce
    image: postgres:16
    ports:
      - 7878:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ecommerce