server:
  port: 8080

spring:
  profiles:
    include:
      - db
      - mail
      - swagger
      - cloudinary
      - custom
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  liquibase:
    enabled: true
    change-log: db/change-log.xml


